# Generated by Django 4.0.2 on 2022-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_condominio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(default=0),
        ),
    ]
