# Generated by Django 4.0.2 on 2022-05-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_condominio', '0002_user_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=12),
        ),
    ]
